# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frbb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='poems',
            field=models.ManyToManyField(blank=True, to='frbb.Poem'),
        ),
    ]
