# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frbb', '0002_auto_20160206_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='withdrawn',
        ),
    ]
