# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frbb', '0003_remove_poem_withdrawn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('word', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('pn', 'plural-noun'), ('n', 'noun'), ('c', 'color'), ('v', 'verb'), ('a', 'adjective')], max_length=2)),
            ],
        ),
    ]
