# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frbb', '0004_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='withdrawn',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=2),
        ),
    ]
