# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frbb', '0005_auto_20160517_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='category',
            field=models.CharField(choices=[('c', 'consent'), ('r', 'random')], default='r', max_length=2),
            preserve_default=False,
        ),
    ]
