# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frbb', '0006_poem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='withdrawn',
            field=models.IntegerField(default=0),
        ),
    ]
